name: Increment Version

on:
  push:
    branches:
      - master

jobs:
  incrementversion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Working Directory
        run: |
          pwd  # Print the current working directory
          find HelloBelle  # Display the directory tree within the 'src' directory
        working-directory: ${{ github.workspace }}

      - name: Increment Version
        run: |
          csproj_file="Hellobelle.csproj"
          bash Hellobelle/tools/increment-version.sh "$csproj_file"
        working-directory: ${{ github.workspace }}
