name: Increment Version

on:
  push:
    branches:
      - master

jobs:
  incrementversion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git user
        run: |
          git config --global user.email "mike.bengil@gmail.com"
          git config --global user.name "Mike Bengil"

      - name: Increment Version
        run: |
          csproj_file="HelloBelle/HelloBelle.csproj"
          bash "HelloBelle/tools/increment-version.sh"
          git add "$csproj_file"
          git commit -m "Increment version"
          git push https://${{ secrets.GIT_VERSION_BELLE }}@github.com/${{ github.repository }}
        working-directory: ${{ github.workspace }}
