name: Increment Version

on:
  push:
    branches:
      - master

jobs:
  incrementversion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Working Directory
        run: |
          pwd  # Print the current working directory
        working-directory: ${{ github.workspace }}

      - name: Increment Version
        run: |
          csproj_file="Hellobelle/Hellobelle.csproj"
          bash Hellobelle/tools/increment-version.sh "$csproj_file"
          git add "$csproj_file"
          git commit -m "Increment version"
          git push
        working-directory: ${{ github.workspace }}
